"""
Road-bridge benchmark: a time-varying, volatile, regime-switching system.

A 30 m road bridge instrumented with one (or more) accelerometers. Its vibration
is driven by inputs that are only partly measured (traffic, wind) and modulated
by environmental and structural conditions that are never measured directly
(deck temperature, frost, damage). This is the running example for the
"critique and expand" demos:

    AR            two structural modes  <->  four AR poles
    TVAR          natural frequencies drift with deck temperature
    + HGF         excitation intensity is volatile (rush hour, storms, quiet nights)
    mixture       abrupt regimes: frozen deck (stiffer), damage (softer)

Physics (deliberately simple, but not generated by any of the demo models)
---------------------------------------------------------------------------
Modal model of a simply supported girder, modes n = 1, 2:

    q''_n + 2 zeta_n w_n(t) q'_n + w_n(t)^2 q_n = F_n(t) / M_n
    acc(x_s, t) = sum_n phi_n(x_s) q''_n(t) + sensor noise,   phi_n(x) = sin(n pi x / L)

    w_n(t) = w_n,ref * [1 + c_n (T_deck - T_ref)]          thermal drift (~0.3 %/degC)
                     * [1 + b_n sigmoid(-T_deck / width)]   frozen asphalt stiffens the deck
                     * [1 - d_n D(t)]                       damage (step at a chosen time)

Generalized forces F_n = traffic + wind buffeting + ambient micro-tremor:
  * traffic : Poisson vehicle arrivals with a weekday rate profile (rush hours),
              cars / vans / trucks, each a moving load m g (1 + bounce) phi_n(x(t));
              the bounce is excited by the expansion joint and by road roughness.
  * wind    : quasi-steady buffeting  ~ rho U B w'(t),  w' turbulence with std I*U,
              so the force variance scales like U^4 -> storms are *volatile*.
  * ambient : small broadband force so the bridge never goes silent.

Time-lapse
----------
Vibration runs in real seconds; the environment clock is compressed:
one scenario hour = `seconds_per_hour` seconds of vibration (default 30 s,
so a 5-day scenario is one hour of 20 Hz data = 72 000 samples). Instantaneous
intensities (vehicles per second, wind speed) stay physical; only their daily
evolution is sped up. The modal decay time (~5 s) is far below 30 s, so each
scenario hour is quasi-stationary, as on a real bridge.

Ground truth returned for the demos: natural frequencies, damping, the implied
AR(4) coefficients, excitation intensity, regime labels -- plus event-driven
sensor streams (deck thermometer, anemometer, weigh-in-motion vehicle events).

Only numpy is required. `python bridge.py` prints a scenario summary.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np

G = 9.81
RHO_AIR = 1.25
WEEKDAYS = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
REGIMES = ("normal", "frozen", "damaged", "frozen + damaged")


# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #

@dataclass
class BridgeParams:
    """The structure and its sensors."""
    L: float = 30.0                                  # span [m]
    width: float = 10.0                              # deck width [m] (wind)
    mass_per_m: float = 8000.0                       # [kg/m]
    f_ref: Tuple[float, ...] = (2.0, 6.0)            # natural freqs at T_ref [Hz]
    zeta: Tuple[float, ...] = (0.015, 0.02)          # damping ratios
    T_ref: float = 10.0                              # reference deck temp [degC]
    temp_coef: Tuple[float, ...] = (-0.003, -0.002)  # rel. freq change per degC
    freeze_gain: Tuple[float, ...] = (0.10, 0.06)    # rel. freq jump when frozen
    freeze_width: float = 0.6                        # degC, sharpness of the knee
    damage_loss: Tuple[float, ...] = (0.06, 0.025)   # rel. freq loss when damaged
    sensor_x: Tuple[float, ...] = (0.3,)             # sensor positions / L
    acc_noise_std: float = 5e-4                      # accelerometer noise [m/s^2]
    ambient_acc_std: float = 8e-4                   # ambient modal force / M [m/s^2]

    @property
    def n_modes(self) -> int:
        return len(self.f_ref)

    @property
    def modal_mass(self) -> float:
        return 0.5 * self.mass_per_m * self.L

    def phi(self, x_frac, n: int):
        """Mode shape n (1-based) at position x/L."""
        return np.sin(n * np.pi * np.asarray(x_frac, float))


@dataclass
class Storm:
    day: int              # 0 = first day of the scenario
    peak_hour: float      # hour of day of the peak
    width_h: float        # std of the Gaussian bump [h]
    peak_speed: float     # extra mean wind at the peak [m/s]
    gustiness: float = 0.06   # extra turbulence intensity at the peak


@dataclass
class Scenario:
    """What happens around the bridge. Defaults: a late-autumn working week."""
    days: int = 5
    start_weekday: int = 0                 # 0 = Monday
    seconds_per_hour: float = 30.0         # time-lapse factor (see module doc)
    fs: float = 20.0                       # accelerometer sample rate [Hz]
    oversample: int = 5                    # internal rate = fs * oversample

    # temperature: daily means (at noon) and diurnal half-ranges, one per day
    temp_mean: Tuple[float, ...] = (9.0, 11.0, 3.0, -1.0, 5.0)
    temp_amp: Tuple[float, ...] = (3.0, 1.5, 5.0, 5.5, 3.0)
    temp_noise: float = 0.6                # slow weather wiggle [degC]
    deck_lag_h: float = 2.0                # thermal inertia of the deck [h]

    # wind
    wind_base: float = 3.5                 # typical mean wind [m/s]
    turb_intensity: float = 0.12           # baseline w'/U
    storms: Tuple[Storm, ...] = (Storm(day=1, peak_hour=15.0, width_h=2.5,
                                       peak_speed=13.0),)

    # traffic
    traffic_peak: float = 1500.0           # vehicles / h at the evening peak
    traffic_night: float = 50.0            # vehicles / h at 3 am
    truck_share: float = 0.08
    speed_kmh: float = 80.0
    icy_traffic_factor: float = 0.6        # fewer, slower vehicles on a frozen deck

    # damage
    damage_at_h: Optional[float] = 4 * 24 + 13.0   # scenario hour (Fri 13:00)
    damage_ramp_h: float = 0.25

    @property
    def hours(self) -> float:
        return 24.0 * self.days

    @property
    def duration_s(self) -> float:
        return self.hours * self.seconds_per_hour


# --------------------------------------------------------------------------- #
# Result container
# --------------------------------------------------------------------------- #

@dataclass
class BridgeSim:
    params: BridgeParams
    scenario: Scenario
    fs: float
    t: np.ndarray            # (N,)   physical time [s]
    hour: np.ndarray         # (N,)   scenario hour since start
    acc: np.ndarray          # (N,S)  measured acceleration [m/s^2]
    acc_true: np.ndarray     # (N,S)  noiseless acceleration
    q: np.ndarray            # (N,M)  modal displacements [m]
    f_nat: np.ndarray        # (N,M)  true natural frequencies [Hz]
    zeta: np.ndarray         # (N,M)  true damping ratios
    ar_true: np.ndarray      # (N,2M) implied AR coefficients (y_k = sum a_i y_{k-i} + e_k)
    exc_rms: np.ndarray      # (N,S)  true excitation intensity at the sensor [m/s^2]
    force_traffic: np.ndarray  # (N,S) traffic load seen by the sensor's modes [m/s^2]
    force_wind: np.ndarray     # (N,S) wind load seen by the sensor's modes [m/s^2]
    U: np.ndarray            # (N,) mean wind speed [m/s]
    turb: np.ndarray         # (N,) turbulence intensity
    T_air: np.ndarray        # (N,) [degC]
    T_deck: np.ndarray       # (N,) [degC]
    traffic_rate: np.ndarray # (N,) expected vehicles per hour
    damage: np.ndarray       # (N,) 0..1
    regime: np.ndarray       # (N,) int index into REGIMES
    vehicles: dict           # arrival table (t, mass, speed, dir, kind)
    temp_obs: dict           # deck thermometer: every 10 scenario-minutes
    wind_obs: dict           # anemometer: 10-minute means
    wim: dict                # weigh-in-motion events (noisy masses)

    @property
    def N(self) -> int:
        return len(self.t)

    @property
    def frozen(self) -> np.ndarray:
        return self.T_deck < 0.0

    def index(self, hour: float) -> int:
        return int(np.clip(round(hour * self.scenario.seconds_per_hour * self.fs),
                           0, self.N - 1))

    def window(self, h0: float, h1: float) -> slice:
        """Sample slice for scenario hours [h0, h1)."""
        return slice(self.index(h0), self.index(h1))

    def label(self, hour: float) -> str:
        """'Tue 14:20' for a scenario hour."""
        d = int(hour // 24)
        hh = hour - 24 * d
        wd = WEEKDAYS[(self.scenario.start_weekday + d) % 7]
        return f"{wd} {int(hh):02d}:{int(round((hh % 1) * 60)) % 60:02d}"


# --------------------------------------------------------------------------- #
# Environment (functions of the scenario clock)
# --------------------------------------------------------------------------- #

def _ou(n: int, dt: float, tau: float, std: float, rng) -> np.ndarray:
    a = np.exp(-dt / tau)
    e = rng.normal(0.0, std * np.sqrt(1 - a * a), n)
    x = np.empty(n)
    x[0] = rng.normal(0.0, std)
    for k in range(1, n):
        x[k] = a * x[k - 1] + e[k]
    return x


def _sigmoid(x):
    return 0.5 * (1.0 + np.tanh(0.5 * x))


def environment(sc: Scenario, pr: BridgeParams, rng, dh: float = 1 / 60):
    """Environment on a one-scenario-minute grid."""
    h = np.arange(0.0, sc.hours + dh, dh)
    hod = h % 24.0
    day = np.minimum((h // 24).astype(int), sc.days - 1)

    # --- temperature: daily means interpolated between noons + diurnal cycle
    noon = 24.0 * np.arange(sc.days) + 12.0
    mean = np.interp(h, noon, np.asarray(sc.temp_mean[:sc.days], float))
    amp = np.interp(h, noon, np.asarray(sc.temp_amp[:sc.days], float))
    T_air = mean + amp * np.cos(2 * np.pi * (hod - 15.0) / 24.0)
    T_air += _ou(len(h), dh, 3.0, sc.temp_noise, rng)
    a = np.exp(-dh / sc.deck_lag_h)
    T_deck = np.empty_like(T_air)
    T_deck[0] = T_air[0]
    for k in range(1, len(h)):
        T_deck[k] = a * T_deck[k - 1] + (1 - a) * T_air[k]

    # --- wind: afternoon breeze + storms + slow fluctuations; gusty turbulence
    U = sc.wind_base * (1.0 + 0.35 * np.cos(2 * np.pi * (hod - 15.0) / 24.0))
    storm = np.zeros_like(h)
    I = np.full_like(h, sc.turb_intensity)
    for s in sc.storms:
        bump = np.exp(-0.5 * ((h - (24.0 * s.day + s.peak_hour)) / s.width_h) ** 2)
        U += s.peak_speed * bump
        I += s.gustiness * bump
        storm = np.maximum(storm, bump)
    U *= np.exp(_ou(len(h), dh, 1.5, 0.15, rng))
    I *= np.exp(_ou(len(h), dh, 0.75, 0.25 + 0.15 * storm.max(), rng))   # gust clusters
    U = np.maximum(U, 0.3)

    # --- traffic: weekday profile, fewer vehicles in storms and on ice
    wd = (sc.start_weekday + day) % 7
    weekend = (wd >= 5).astype(float)
    prof = (np.exp(-0.5 * ((hod - 8.0) / 1.1) ** 2) * 0.9
            + np.exp(-0.5 * ((hod - 13.0) / 3.0) ** 2) * 0.45
            + np.exp(-0.5 * ((hod - 17.5) / 1.4) ** 2) * 1.0)
    prof *= (1.0 - 0.6 * weekend)
    rate = sc.traffic_night + (sc.traffic_peak - sc.traffic_night) * prof
    icy = _sigmoid(-(T_deck - 0.5) / 0.4)
    rate *= (1.0 - (1.0 - sc.icy_traffic_factor) * icy) * (1.0 - 0.3 * storm)

    # --- damage
    if sc.damage_at_h is None:
        D = np.zeros_like(h)
    else:
        D = np.clip((h - sc.damage_at_h) / max(sc.damage_ramp_h, 1e-6), 0.0, 1.0)

    return dict(h=h, T_air=T_air, T_deck=T_deck, U=U, I=I, rate=rate,
                icy=icy, storm=storm, D=D)


def modal_frequencies(pr: BridgeParams, T_deck, D):
    """True natural frequencies [Hz], shape (..., n_modes)."""
    T = np.asarray(T_deck, float)[..., None]
    D = np.asarray(D, float)[..., None]
    f = np.asarray(pr.f_ref)
    c = np.asarray(pr.temp_coef)
    b = np.asarray(pr.freeze_gain)
    d = np.asarray(pr.damage_loss)
    return (f * (1.0 + c * (T - pr.T_ref))
              * (1.0 + b * _sigmoid(-T / pr.freeze_width))
              * (1.0 - d * D))


def ar_from_modes(f_nat, zeta, fs):
    """AR coefficients implied by the modal poles: y_k = sum_i a_i y_{k-i} + e_k.

    Each mode contributes the factor (1 - 2 r cos(th) z^-1 + r^2 z^-2),
    r = exp(-zeta w / fs), th = w sqrt(1 - zeta^2) / fs.
    """
    f_nat = np.atleast_2d(f_nat)
    zeta = np.broadcast_to(zeta, f_nat.shape)
    w = 2 * np.pi * f_nat
    r = np.exp(-zeta * w / fs)
    th = w * np.sqrt(1 - zeta ** 2) / fs
    poly = np.ones((f_nat.shape[0], 1))
    for n in range(f_nat.shape[1]):
        quad = np.stack([np.ones_like(r[:, n]), -2 * r[:, n] * np.cos(th[:, n]),
                         r[:, n] ** 2], axis=1)
        out = np.zeros((poly.shape[0], poly.shape[1] + 2))
        for i in range(poly.shape[1]):
            out[:, i:i + 3] += poly[:, i:i + 1] * quad
        poly = out
    return -poly[:, 1:]


# --------------------------------------------------------------------------- #
# Loads
# --------------------------------------------------------------------------- #

def _vehicle_table(sc: Scenario, env, rng) -> dict:
    """Non-homogeneous Poisson arrivals (thinning) on the physical clock."""
    T = sc.duration_s
    lam = lambda t: np.interp(t / sc.seconds_per_hour, env["h"], env["rate"]) / 3600.0
    lam_max = env["rate"].max() / 3600.0
    n_cand = rng.poisson(lam_max * T)
    tc = np.sort(rng.uniform(0.0, T, n_cand))
    t = tc[rng.uniform(0, 1, n_cand) < lam(tc) / lam_max]
    n = len(t)

    u = rng.uniform(0, 1, n)
    kind = np.where(u < sc.truck_share, 2, np.where(u < sc.truck_share + 0.08, 1, 0))
    mass = np.where(kind == 0, 1500.0 * rng.lognormal(0, 0.15, n),
            np.where(kind == 1, 3500.0 * rng.lognormal(0, 0.15, n),
                     np.clip(22000.0 * rng.lognormal(0, 0.35, n), 9000, 44000)))
    icy = np.interp(t / sc.seconds_per_hour, env["h"], env["icy"])
    speed = (sc.speed_kmh / 3.6) * rng.normal(1.0, 0.08, n) * (1.0 - 0.25 * icy)
    speed *= np.where(kind == 2, 0.9, 1.0)
    direction = rng.choice([-1, 1], n)
    f_bounce = np.where(kind == 2, rng.uniform(1.5, 3.0, n), rng.uniform(1.2, 2.5, n))
    return dict(t=t, mass=mass, speed=speed, dir=direction, kind=kind,
                f_bounce=f_bounce, phase=rng.uniform(0, 2 * np.pi, n))


def _traffic_force(pr: BridgeParams, veh: dict, fs_i: float, N_i: int, rng):
    """Generalized traffic force per unit modal mass, shape (N_i, n_modes)."""
    M = pr.modal_mass
    F = np.zeros((N_i, pr.n_modes))
    for k in range(len(veh["t"])):
        t0, v = veh["t"][k], veh["speed"][k]
        i0 = int(np.ceil(t0 * fs_i))
        i1 = min(int(np.floor((t0 + pr.L / v) * fs_i)), N_i - 1)
        if i1 <= i0:
            continue
        tau = np.arange(i0, i1 + 1) / fs_i - t0
        x = v * tau / pr.L
        if veh["dir"][k] < 0:
            x = 1.0 - x
        rough = np.convolve(rng.normal(0, 1, len(tau) + 6), np.ones(7) / np.sqrt(7), "valid")
        bounce = (0.10 * np.exp(-tau / 1.0)
                  * np.sin(2 * np.pi * veh["f_bounce"][k] * tau + veh["phase"][k])
                  + 0.03 * rough)
        P = veh["mass"][k] * G * (1.0 + bounce) / M
        for n in range(pr.n_modes):
            F[i0:i1 + 1, n] += P * pr.phi(x, n + 1)
    return F


def _block_first_order(lam_b, gain_b, u, nb, z0=0.0):
    """z_{k+1} = lam z_k + gain u_k with block-constant coefficients.

    Vectorized within blocks, sequential across blocks. Returns z_k for all k
    (the state *before* input u_k is applied).
    """
    B = len(lam_b)
    U = u.reshape(B, nb)
    k = np.arange(nb + 1)
    lp = lam_b[:, None] ** k[None, :]                    # (B, nb+1)
    S = np.zeros((B, nb + 1), dtype=np.result_type(lam_b, u))
    S[:, 1:] = np.cumsum(U / lp[:, :nb], axis=1)
    zp = gain_b[:, None] * lp / lam_b[:, None] * S       # particular, zero init
    zp[:, 0] = 0.0
    z_init = np.empty(B, dtype=zp.dtype)
    z = z0
    for b in range(B):
        z_init[b] = z
        z = lp[b, nb] * z + zp[b, nb]
    Z = lp[:, :nb] * z_init[:, None] + zp[:, :nb]
    return Z.reshape(-1)


def _modal_response(f_hz_b, zeta_b, F, fs_i, nb):
    """Exact ZOH response of one SDOF mode with block-constant parameters.

    Uses z = q' - conj(p) q, which obeys z' = p z + F (p = -zeta w + i w_d);
    then q = Im(z)/w_d and q' = Re(z) - zeta w q. The physical state (q, q')
    is carried across blocks when the parameters change.
    """
    dt = 1.0 / fs_i
    B = len(f_hz_b)
    w = 2 * np.pi * f_hz_b
    wd = w * np.sqrt(1 - zeta_b ** 2)
    p = -zeta_b * w + 1j * wd
    lam = np.exp(p * dt)
    gain = (lam - 1.0) / p
    U = F.reshape(B, nb)
    k = np.arange(nb + 1)
    lp = lam[:, None] ** k[None, :]
    S = np.zeros((B, nb + 1), dtype=complex)
    S[:, 1:] = np.cumsum(U / lp[:, :nb], axis=1)
    zp = gain[:, None] * lp / lam[:, None] * S
    zp[:, 0] = 0.0

    q = qd = 0.0
    z_init = np.empty(B, dtype=complex)
    for b in range(B):
        z0 = qd - np.conj(p[b]) * q                 # physical state -> this block's z
        z_init[b] = z0
        z_end = lp[b, nb] * z0 + zp[b, nb]
        q = z_end.imag / wd[b]
        qd = z_end.real - zeta_b[b] * w[b] * q
    Z = lp[:, :nb] * z_init[:, None] + zp[:, :nb]
    wd_s = np.repeat(wd, nb)
    zw_s = np.repeat(zeta_b * w, nb)
    w2_s = np.repeat(w ** 2, nb)
    Z = Z.reshape(-1)
    q = Z.imag / wd_s
    qd = Z.real - zw_s * q
    qdd = -2 * zw_s * qd - w2_s * q + F
    return q, qd, qdd


def _lowpass_decimate(x, factor, cutoff_frac=0.85, taps=201):
    """Windowed-sinc anti-alias filter, then keep every `factor`-th sample."""
    if factor == 1:
        return x
    fc = cutoff_frac * 0.5 / factor              # cycles / internal sample
    n = np.arange(taps) - (taps - 1) / 2
    h = 2 * fc * np.sinc(2 * fc * n) * np.hamming(taps)
    h /= h.sum()
    y = np.apply_along_axis(lambda c: np.convolve(c, h, mode="same"), 0, x)
    return y[::factor]


# --------------------------------------------------------------------------- #
# Simulation
# --------------------------------------------------------------------------- #

def simulate(scenario: Optional[Scenario] = None,
             params: Optional[BridgeParams] = None,
             seed: int = 0, block_s: float = 0.5) -> BridgeSim:
    sc = scenario or Scenario()
    pr = params or BridgeParams()
    rng = np.random.default_rng(seed)

    fs, R = sc.fs, sc.oversample
    fs_i = fs * R
    nb = int(round(block_s * fs_i))
    B = int(np.ceil(sc.duration_s * fs_i / nb))
    N_i = B * nb
    t_i = np.arange(N_i) / fs_i
    h_i = t_i / sc.seconds_per_hour

    env = environment(sc, pr, rng)
    at = lambda key, h: np.interp(h, env["h"], env[key])

    # ---- loads (per unit modal mass) -----------------------------------------
    veh = _vehicle_table(sc, env, rng)
    F_traffic = _traffic_force(pr, veh, fs_i, N_i, rng)

    U_i, I_i = at("U", h_i), at("I", h_i)
    F_wind = np.zeros((N_i, pr.n_modes))
    coh = (0.4, 0.2, 0.1, 0.05)                     # effective span coherence per mode
    for n in range(pr.n_modes):
        # unit-variance turbulence with integral time L_w / U
        tau_w = 15.0 / np.maximum(U_i[::nb], 1.0)
        a = np.exp(-1.0 / (fs_i * tau_w))
        xi = _block_first_order(a, np.sqrt(1 - a ** 2),
                                rng.normal(0, 1, N_i), nb).real
        w_turb = I_i * U_i * xi
        F_wind[:, n] = (2.0 * RHO_AIR * U_i * pr.width * w_turb
                        * pr.L * coh[n % len(coh)] / pr.modal_mass)

    F_amb = rng.normal(0, pr.ambient_acc_std, (N_i, pr.n_modes))
    F_amb = np.apply_along_axis(lambda c: np.convolve(c, np.ones(3) / np.sqrt(3), "same"),
                                0, F_amb)
    F = F_traffic + F_wind + F_amb

    # ---- structure -------------------------------------------------------------
    h_b = (np.arange(B) + 0.5) * nb / fs_i / sc.seconds_per_hour
    T_b, D_b = at("T_deck", h_b), at("D", h_b)
    f_b = modal_frequencies(pr, T_b, D_b)          # (B, M)
    z_b = np.broadcast_to(np.asarray(pr.zeta), f_b.shape)

    q_i = np.zeros((N_i, pr.n_modes))
    qdd_i = np.zeros((N_i, pr.n_modes))
    for n in range(pr.n_modes):
        q, _, qdd = _modal_response(f_b[:, n], np.ascontiguousarray(z_b[:, n]),
                                    F[:, n], fs_i, nb)
        q_i[:, n], qdd_i[:, n] = q, qdd

    S = len(pr.sensor_x)
    Phi = np.array([[pr.phi(x, n + 1) for n in range(pr.n_modes)] for x in pr.sensor_x])  # (S,M)
    acc_i = qdd_i @ Phi.T
    exc_i = F @ Phi.T
    trf_i = F_traffic @ Phi.T
    wnd_i = F_wind @ Phi.T

    # ---- to the sensor rate ------------------------------------------------------
    N = int(np.floor(sc.duration_s * fs))
    acc_true = _lowpass_decimate(acc_i, R)[:N]
    q_out = _lowpass_decimate(q_i, R)[:N]
    acc = acc_true + rng.normal(0, pr.acc_noise_std, acc_true.shape)

    def rms_env(x, win_s=4.0):
        k = max(1, int(win_s * fs_i))
        ker = np.ones(k) / k
        return np.sqrt(np.apply_along_axis(lambda c: np.convolve(c ** 2, ker, "same"), 0, x))[::R][:N]

    exc_rms = rms_env(exc_i)
    force_traffic = trf_i[::R][:N]
    force_wind = wnd_i[::R][:N]

    t = np.arange(N) / fs
    hour = t / sc.seconds_per_hour
    T_deck = at("T_deck", hour)
    D = at("D", hour)
    f_nat = modal_frequencies(pr, T_deck, D)
    zeta = np.broadcast_to(np.asarray(pr.zeta), f_nat.shape).copy()
    ar_true = ar_from_modes(f_nat, zeta, fs)
    frozen = T_deck < 0.0
    damaged = D > 0.5
    regime = frozen.astype(int) + 2 * damaged.astype(int)

    # ---- event-driven side sensors -------------------------------------------
    step_h = 10 / 60
    obs_h = np.arange(step_h, sc.hours + 1e-9, step_h)
    temp_obs = dict(t=obs_h * sc.seconds_per_hour,
                    value=at("T_deck", obs_h) + rng.normal(0, 0.2, len(obs_h)))
    Uw = np.array([env["U"][(env["h"] > h - step_h) & (env["h"] <= h)].mean() for h in obs_h])
    wind_obs = dict(t=obs_h * sc.seconds_per_hour,
                    value=Uw * rng.normal(1.0, 0.05, len(obs_h)))
    wim = dict(t=veh["t"].copy(), mass=veh["mass"] * rng.normal(1.0, 0.08, len(veh["t"])),
               speed=veh["speed"].copy(), kind=veh["kind"].copy())

    return BridgeSim(
        params=pr, scenario=sc, fs=fs, t=t, hour=hour, acc=acc, acc_true=acc_true,
        q=q_out, f_nat=f_nat, zeta=zeta, ar_true=ar_true, exc_rms=exc_rms,
        force_traffic=force_traffic, force_wind=force_wind,
        U=at("U", hour), turb=at("I", hour), T_air=at("T_air", hour), T_deck=T_deck,
        traffic_rate=at("rate", hour), damage=D, regime=regime,
        vehicles=veh, temp_obs=temp_obs, wind_obs=wind_obs, wim=wim)


# --------------------------------------------------------------------------- #
# Helpers for the demos
# --------------------------------------------------------------------------- #

def to_table(sim: BridgeSim) -> dict:
    """Flat columns (e.g. for pandas / CSV / Julia). Sensor 0 only."""
    cols = dict(t=sim.t, hour=sim.hour, acc=sim.acc[:, 0], acc_true=sim.acc_true[:, 0],
                T_deck=sim.T_deck, T_air=sim.T_air, wind=sim.U, turbulence=sim.turb,
                traffic_rate=sim.traffic_rate, exc_rms=sim.exc_rms[:, 0],
                damage=sim.damage, regime=sim.regime)
    for n in range(sim.f_nat.shape[1]):
        cols[f"f{n + 1}"] = sim.f_nat[:, n]
    for i in range(sim.ar_true.shape[1]):
        cols[f"a{i + 1}"] = sim.ar_true[:, i]
    return cols


def save_csv(sim: BridgeSim, path: str) -> str:
    cols = to_table(sim)
    np.savetxt(path, np.column_stack(list(cols.values())), delimiter=",",
               header=",".join(cols), comments="", fmt="%.7g")
    return path


def send_on_delta(t, x, delta: float):
    """Event-driven sampling: report x only when it moved by more than `delta`."""
    keep = [0]
    last = x[0]
    for k in range(1, len(x)):
        if abs(x[k] - last) > delta:
            keep.append(k)
            last = x[k]
    keep = np.asarray(keep)
    return np.asarray(t)[keep], np.asarray(x)[keep]


def psd(x, fs: float, nseg: int = 256):
    """Welch PSD (Hann, 50 % overlap). Returns (freq, power)."""
    x = np.asarray(x, float)
    nseg = min(nseg, len(x))
    step = nseg // 2
    win = np.hanning(nseg)
    segs = [x[i:i + nseg] for i in range(0, len(x) - nseg + 1, step)]
    P = np.mean([np.abs(np.fft.rfft((s - s.mean()) * win)) ** 2 for s in segs], axis=0)
    P /= fs * (win ** 2).sum()
    return np.fft.rfftfreq(nseg, 1 / fs), P


def summary(sim: BridgeSim) -> str:
    lines = [f"{sim.scenario.days}-day scenario, {sim.N} samples at {sim.fs:g} Hz "
             f"({sim.scenario.seconds_per_hour:g} s per scenario hour), "
             f"{len(sim.vehicles['t'])} vehicles"]
    for d in range(sim.scenario.days):
        s = sim.window(24 * d, 24 * (d + 1))
        a = sim.acc[s, 0]
        rms_h = np.sqrt(np.mean(a[: len(a) // 24 * 24].reshape(24, -1) ** 2, axis=1))
        lines.append(
            f"  {sim.label(24 * d)[:3]}: T_deck {sim.T_deck[s].min():5.1f}..{sim.T_deck[s].max():5.1f} C"
            f" | U max {sim.U[s].max():4.1f} m/s"
            f" | f1 {sim.f_nat[s, 0].min():.3f}..{sim.f_nat[s, 0].max():.3f} Hz"
            f" | hourly acc RMS {rms_h.min()*1e3:6.1f}..{rms_h.max()*1e3:6.1f} mm/s^2"
            f" | frozen {sim.frozen[s].mean()*24:4.1f} h")
    return "\n".join(lines)


if __name__ == "__main__":
    import time
    t0 = time.time()
    sim = simulate(seed=0)
    print(f"simulated in {time.time() - t0:.2f} s")
    print(summary(sim))

    save_csv(sim, "data/sim_001.csv")
